### ISSUE TITLE
Docs for how the users table has to look like

### ISSUE THREAD

**Issue by inoas** [FriendsOfCake/crud-users#16]
Are there any? It could be very concise sql create table/schema snippet, or a cakephp/migrations based migration.

**Comment by ADmad** [comment]
The plugin doesn't have any docs. It doesn't enforce any particular schema for users table. All actions are generic enough to work with whatever you want.

**Comment by inoas** [comment]
tokens seems to be a field
https://github.com/FriendsOfCake/crud-users/blob/master/src/Traits/VerifyTrait.php#L51
verified another
https://github.com/FriendsOfCake/crud-users/blob/master/src/Action/VerifyAction.php#L82

1. Wrong, right?
2. Could these be made configurable in any way? if not `is_verified` would be nice over just `verified`

**Comment by ADmad** [comment]
1.  Since the find method is configurable you can change the conditions in your custom finder.

2. You can use beforeSave event to set another field.

For convenience though we can make those fields configurable through action config.

**Comment by inoas** [comment]
That would be lovely!

For now is it that - or are there other fields to be aware of?

**Comment by inoas** [comment]
In a hindsight I think docs alone would do. E.g. how to specify the `finder` and a 1-2 lines finder which specifies the fields.

Same for how to utilize beforeSave.

**Comment by ADmad** [comment]
It's unlikely anyone is going to find the time soon to write docs for this plugin.

**Comment by inoas** [comment]
If I get to use it and understand it by doing so, then I could.
If you would be so kind and add this in a way you consider to be right, after merging my docs PR:

> Since the find method is configurable you can change the conditions in your custom finder.
> You can use beforeSave event to set another field.

? 

Thanks.

**Comment by josegonzalez** [comment]
These were added in your pull request.
