### ISSUE TITLE
Make a 0.2.0 release

### ISSUE THREAD

**Issue by inoas** [FriendsOfCake/crud-users#18]
When doing composer install friendsofcake/crud-users you will get 0.1.0 which is broken - it has simple bugs in ForgotPasswordAction and there isn't even a VerifyAction

**Comment by inoas** [comment]
Also the error will look like this when the missing action cannot be found (an issue with CRUD itself?)
<img width="1680" alt="screen shot 2016-08-22 at 23 24 52" src="https://cloud.githubusercontent.com/assets/20972207/17872302/baf35dac-68bf-11e6-8d0b-59dbbe365a2c.png">

**Comment by josegonzalez** [comment]
Just made a release.

**Comment by inoas** [comment]
Thanks!
