### ISSUE TITLE
Broken Docs link

### ISSUE THREAD

**Issue by raul338** [FriendsOfCake/crud-users#25]
https://crud-users.readthedocs.io/en/latest/ throws 
```
SORRY
This page does not exist yet.
```

**Comment by josegonzalez** [comment]
That link looks fine to me?

**Comment by ADmad** [comment]
Me too. Must have been some temporary issue with readthedocs.io.

**Comment by jippi** [comment]
I still see it :)

**Comment by jippi** [comment]
![image](https://user-images.githubusercontent.com/22841/28911607-5b4088d0-7831-11e7-96b9-bc39e6c7acb2.png)

**Comment by ADmad** [comment]
I too got the page shown above by @jippi but after couple of refreshes the actual docs page showed up.

**Comment by josegonzalez** [comment]
I don't think there is much we can do here other than start self-hosting our own docs.

**Comment by jippi** [comment]
works for me now :)
