### ISSUE TITLE
Feature: Add ChangePasswordAction

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud-users#3]

**Comment by josegonzalez** [comment]
How would this thing work?

**Comment by ADmad** [comment]
Generate token, email link with token, when link is used show form to enter new password if token not expired. Something like that :)

**Comment by Phillaf** [comment]
Could be done with the token from friendsofcake/authenticate, here's how I do it
https://github.com/gintonicweb/users/blob/master/src/Controller/UsersController.php#L209

**Comment by jadb** [comment]
This could use https://github.com/UseMuffin/Tokenize ;)

**Comment by lorenzo** [comment]
:+1:

**Comment by ADmad** [comment]
#6 and #13 take care of this.
